-- MySQL Script generated by MySQL Workbench
-- Thu Dec 21 23:56:19 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema crawl_data
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema crawl_data
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `crawl_data` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `crawl_data` ;

-- -----------------------------------------------------
-- Table `crawl_data`.`job_data`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crawl_data`.`job_data` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Title` VARCHAR(255) NULL DEFAULT NULL,
  `Company_Name` VARCHAR(255) NULL DEFAULT NULL,
  `Job` VARCHAR(255) NULL DEFAULT NULL,
  `Place` VARCHAR(255) NULL DEFAULT NULL,
  `Number_Employee` VARCHAR(255) NULL DEFAULT NULL,
  `Experience` VARCHAR(255) NULL DEFAULT NULL,
  `Level` VARCHAR(255) NULL DEFAULT NULL,
  `Salary` VARCHAR(255) NULL DEFAULT NULL,
  `Education` VARCHAR(255) NULL DEFAULT NULL,
  `Description` TEXT NULL DEFAULT NULL,
  `Requirement` TEXT NULL DEFAULT NULL,
  `Deadline` VARCHAR(255) NULL DEFAULT NULL,
  `Source_Picture` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 224
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
