DROP DATABASE IF EXISTS pbl3;
CREATE DATABASE IF NOT EXISTS pbl3 CHAR SET utf8mb4;
-- create table company 
DROP TABLE IF EXISTS COMPANY;
CREATE TABLE IF NOT EXISTS COMPANY
(
	ID INT NOT NULL AUTO_INCREMENT,
    `NAME` VARCHAR(256) NOT NULL,
	ADDRESS TEXT,	
    INDUSTRY_ID INT NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT UNQ_NAME UNIQUE(`NAME`),
    CONSTRAINT FK_COMPANY_INDUSTRY FOREIGN KEY (INDUSTRY_ID) REFERENCES INDUSTRY(ID)
);


SELECT * FROM `rank`;
SELECT * FROM company;
SELECT * FROM industry;
SELECT * FROM recruitment_detail;


-- create table industry
DROP TABLE IF EXISTS INDUSTRY;
CREATE TABLE IF NOT EXISTS INDUSTRY 
(
	ID INT NOT NULL AUTO_INCREMENT,
    `NAME` VARCHAR(200) NOT NULL,
    PRIMARY KEY(ID),
	CONSTRAINT UNQ_INDUSTRY_NAME UNIQUE(`NAME`)
);

-- create table title: vị trí việc làm
DROP TABLE IF EXISTS `RANK`;
CREATE TABLE IF NOT EXISTS `RANK` 
(
	ID INT NOT NULL AUTO_INCREMENT,
    `NAME` VARCHAR(200) NOT NULL,
    CONSTRAINT UNQ_JT_NAME UNIQUE(`NAME`),
    PRIMARY KEY(ID)
);

DROP TABLE IF EXISTS RECRUITMENT_DETAIL;
CREATE TABLE IF NOT EXISTS RECRUITMENT_DETAIL
(
	ID INT NOT NULL AUTO_INCREMENT,
    JOB_NAME VARCHAR(255) NOT NULL,
    COMPANY_ID INT NOT NULL,
    RANK_ID INT NOT NULL,
    SALARY VARCHAR(255),
    POSTED_DATE_AT VARCHAR(255),
    DEADLINE_TO_APPLY VARCHAR(255), 
    EXPERIENCE VARCHAR(255),
    NUMBER_OF_RECRUITMENT VARCHAR(100),
    AGE_RANGE VARCHAR(100),
    GENDER VARCHAR(10),
    QUALIFICATION VARCHAR(255),
    PROBATION_PERIOD VARCHAR(255),
    LOCATION TEXT,
    `DESCRIPTION` TEXT,
    BENEFIT TEXT,
    REQUIREMENT TEXT,
    SOURCE_PICTURE TEXT,	
	PRIMARY KEY(ID),
    CONSTRAINT FK_RD_COMPANY    FOREIGN KEY (COMPANY_ID)   REFERENCES COMPANY(ID),
    CONSTRAINT FK_RD_RANK  		FOREIGN KEY (RANK_ID)	   REFERENCES `RANK`(ID)
);

DROP TABLE IF EXISTS `USER`;
CREATE TABLE IF NOT EXISTS `USER`
(
	ID INT NOT NULL AUTO_INCREMENT,
    `NAME` VARCHAR(100) NOT NULL,
    GENDER BIT NOT NULL,
    AGE INT NOT NULL,
    PHONE VARCHAR(20) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    `PASSWORD` VARCHAR(100) NOT NULL,
    ADDRESS TEXT NOT NULL,
    AVATAR TEXT,
    CREATED_AT DATETIME NOT NULL,
    UPDATED_AT DATETIME NOT NULL,
    ROLE_ID INT NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT CHK_GENDER CHECK (GENDER IN (0, 1)),
    CONSTRAINT FK_USER_ROLE FOREIGN KEY (ROLE_ID) REFERENCES `ROLE` (ID)
);

DROP TABLE IF EXISTS `ROLE`;
CREATE TABLE IF NOT EXISTS `ROLE`
(
	ID INT NOT NULL AUTO_INCREMENT,
    `DESC` VARCHAR(100),
    PRIMARY KEY(ID)
);


