DROP DATABASE IF EXISTS pbl3;
CREATE DATABASE IF NOT EXISTS pbl3 CHAR SET utf8mb4;
-- create table company 
DROP TABLE IF EXISTS COMPANY;
CREATE TABLE IF NOT EXISTS COMPANY
(
	ID INT AUTO_INCREMENT,
    `NAME` VARCHAR(256) NOT NULL,
	ADDRESS TEXT,	
    CAREER_ID INT NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT UNQ_NAME UNIQUE(`NAME`),
    CONSTRAINT FK_COMPANY_CAREER FOREIGN KEY (CAREER_ID) REFERENCES CAREER(ID)
);


-- create table industry
DROP TABLE IF EXISTS CAREER;
CREATE TABLE IF NOT EXISTS CAREER 
(
	ID INT AUTO_INCREMENT,
    `NAME` VARCHAR(200) NOT NULL,
    PRIMARY KEY(ID),
	CONSTRAINT UNQ_CAREER_NAME UNIQUE(`NAME`)
);

-- create table title: vị trí việc làm
DROP TABLE IF EXISTS `POSITION`;
CREATE TABLE IF NOT EXISTS `POSITION`
(
	ID INT AUTO_INCREMENT,
    `NAME` VARCHAR(200) NOT NULL,
    CONSTRAINT UNQ_JT_NAME UNIQUE(`NAME`),
    PRIMARY KEY(ID)
);


DROP TABLE IF EXISTS INFO_RECRUITMENT_DETAIL;
CREATE TABLE IF NOT EXISTS INFO_RECRUITMENT_DETAIL
(
	ID INT AUTO_INCREMENT,
    JOB_NAME VARCHAR(255) NOT NULL,
    COMPANY_ID INT NOT NULL,
    POSITION_ID INT NOT NULL,
    SALARY VARCHAR(255),
    POSTED_DATE_AT VARCHAR(255),
    DEADLINE_TO_APPLY VARCHAR(255), 
    EXPERIENCE VARCHAR(255),
    NUMBER_OF_RECRUITMENT VARCHAR(100),
    AGE_RANGE VARCHAR(100),
    GENDER VARCHAR(10),
    QUALIFICATION VARCHAR(255),
    PROBATION_PERIOD VARCHAR(255),
    LOCATION TEXT,
    `DESCRIPTION` TEXT,
    BENEFIT TEXT,
    REQUIREMENT TEXT,
    SOURCE_PICTURE TEXT,	
	PRIMARY KEY(ID),
    CONSTRAINT FK_RD_COMPANY    FOREIGN KEY (COMPANY_ID)   REFERENCES COMPANY(ID),
    CONSTRAINT FK_RD_POSITION 	FOREIGN KEY (POSITION_ID)  REFERENCES `POSITION`(ID)
);

DROP TABLE IF EXISTS `USER`;
CREATE TABLE IF NOT EXISTS `USER`
(
	ID INT AUTO_INCREMENT,
    `NAME` VARCHAR(100) NOT NULL,
    GENDER BIT NOT NULL,
    AGE INT NOT NULL,
    PHONE VARCHAR(20) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    `PASSWORD` VARCHAR(100) NOT NULL,
    ADDRESS TEXT NOT NULL,
    AVATAR TEXT,
    CREATED_AT DATETIME NOT NULL,
    UPDATED_AT DATETIME NOT NULL,
    ROLE_ID INT NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT CHK_GENDER CHECK (GENDER IN (0, 1)),
    CONSTRAINT FK_USER_ROLE FOREIGN KEY (ROLE_ID) REFERENCES `ROLE` (ID)
);

DROP TABLE IF EXISTS `ROLE`;
CREATE TABLE IF NOT EXISTS `ROLE`
(
	ID INT AUTO_INCREMENT,
    `DESC` VARCHAR(100),	
    PRIMARY KEY(ID)
);




